/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  serial,
  varchar,
  timestamp,
  numeric,
  boolean,
  integer,
  type AnyPgColumn,
  jsonb,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum_users_role = pgEnum('enum_users_role', ['admin', 'author', 'user'])
export const enum_comments_status = pgEnum('enum_comments_status', [
  'pending',
  'approved',
  'rejected',
])
export const enum_likes_type = pgEnum('enum_likes_type', ['like', 'dislike'])
export const enum_post_logs_action = pgEnum('enum_post_logs_action', ['create', 'update', 'delete'])
export const enum_posts_status = pgEnum('enum_posts_status', [
  'draft',
  'published',
  'pending_approval',
])
export const enum_post_translation_entries_locale = pgEnum('enum_post_translation_entries_locale', [
  'en',
  'zh',
  'hi',
  'es',
  'fr',
  'ar',
])
export const enum_notifications_type = pgEnum('enum_notifications_type', [
  'comment',
  'reply',
  'system',
])

export const admin = pgTable(
  'admin',
  {
    id: serial('id').primaryKey(),
    displayName: varchar('display_name').notNull(),
    deleted_at: timestamp('deleted_at', { mode: 'string', withTimezone: true, precision: 3 }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts').default('0'),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => ({
    admin_updated_at_idx: index('admin_updated_at_idx').on(columns.updatedAt),
    admin_created_at_idx: index('admin_created_at_idx').on(columns.createdAt),
    admin_email_idx: uniqueIndex('admin_email_idx').on(columns.email),
  }),
)

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    displayName: varchar('display_name'),
    username: varchar('username').notNull(),
    bio: varchar('bio'),
    verified: boolean('verified').notNull().default(false),
    profileImage: varchar('profile_image'),
    role: enum_users_role('role').notNull().default('user'),
    socialLinks: varchar('social_links'),
    email: varchar('email').notNull(),
    uid: varchar('uid').notNull(),
    lastLogin: timestamp('last_login', { mode: 'string', withTimezone: true, precision: 3 }),
    deleted_at: timestamp('deleted_at', { mode: 'string', withTimezone: true, precision: 3 }),
    verificationOtpHash: varchar('verification_otp_hash'),
    verificationOtpExpiresAt: timestamp('verification_otp_expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    verificationOtpSentAt: timestamp('verification_otp_sent_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    users_username_idx: uniqueIndex('users_username_idx').on(columns.username),
    users_profile_image_idx: index('users_profile_image_idx').on(columns.profileImage),
    users_email_idx: uniqueIndex('users_email_idx').on(columns.email),
    users_uid_idx: uniqueIndex('users_uid_idx').on(columns.uid),
    users_updated_at_idx: index('users_updated_at_idx').on(columns.updatedAt),
    users_created_at_idx: index('users_created_at_idx').on(columns.createdAt),
  }),
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize'),
    width: numeric('width'),
    height: numeric('height'),
    focalX: numeric('focal_x'),
    focalY: numeric('focal_y'),
  },
  (columns) => ({
    media_updated_at_idx: index('media_updated_at_idx').on(columns.updatedAt),
    media_created_at_idx: index('media_created_at_idx').on(columns.createdAt),
    media_filename_idx: uniqueIndex('media_filename_idx').on(columns.filename),
  }),
)

export const categories = pgTable(
  'categories',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    slug: varchar('slug').notNull(),
    parent: integer('parent_id').references((): AnyPgColumn => categories.id, {
      onDelete: 'set null',
    }),
    deleted_at: timestamp('deleted_at', { mode: 'string', withTimezone: true, precision: 3 }),
    isVisible: boolean('is_visible').notNull().default(true),
    createdBy: integer('created_by_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    categories_name_idx: uniqueIndex('categories_name_idx').on(columns.name),
    categories_slug_idx: uniqueIndex('categories_slug_idx').on(columns.slug),
    categories_parent_idx: index('categories_parent_idx').on(columns.parent),
    categories_created_by_idx: index('categories_created_by_idx').on(columns.createdBy),
    categories_updated_at_idx: index('categories_updated_at_idx').on(columns.updatedAt),
    categories_created_at_idx: index('categories_created_at_idx').on(columns.createdAt),
  }),
)

export const comments = pgTable(
  'comments',
  {
    id: serial('id').primaryKey(),
    post: integer('post_id')
      .notNull()
      .references(() => posts.id, {
        onDelete: 'set null',
      }),
    user: integer('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    content: varchar('content').notNull(),
    status: enum_comments_status('status').default('pending'),
    parent: integer('parent_id').references((): AnyPgColumn => comments.id, {
      onDelete: 'set null',
    }),
    language: varchar('language').default('en'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    comments_post_idx: index('comments_post_idx').on(columns.post),
    comments_user_idx: index('comments_user_idx').on(columns.user),
    comments_parent_idx: index('comments_parent_idx').on(columns.parent),
    comments_updated_at_idx: index('comments_updated_at_idx').on(columns.updatedAt),
    comments_created_at_idx: index('comments_created_at_idx').on(columns.createdAt),
  }),
)

export const likes = pgTable(
  'likes',
  {
    id: serial('id').primaryKey(),
    post: integer('post_id')
      .notNull()
      .references(() => posts.id, {
        onDelete: 'set null',
      }),
    user: integer('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    type: enum_likes_type('type').notNull().default('like'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    likes_post_idx: index('likes_post_idx').on(columns.post),
    likes_user_idx: index('likes_user_idx').on(columns.user),
    likes_updated_at_idx: index('likes_updated_at_idx').on(columns.updatedAt),
    likes_created_at_idx: index('likes_created_at_idx').on(columns.createdAt),
  }),
)

export const post_logs = pgTable(
  'post_logs',
  {
    id: serial('id').primaryKey(),
    post: integer('post_id')
      .notNull()
      .references(() => posts.id, {
        onDelete: 'set null',
      }),
    user: integer('user_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    action: enum_post_logs_action('action').notNull(),
    timestamp: timestamp('timestamp', { mode: 'string', withTimezone: true, precision: 3 }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    post_logs_post_idx: index('post_logs_post_idx').on(columns.post),
    post_logs_user_idx: index('post_logs_user_idx').on(columns.user),
    post_logs_updated_at_idx: index('post_logs_updated_at_idx').on(columns.updatedAt),
    post_logs_created_at_idx: index('post_logs_created_at_idx').on(columns.createdAt),
  }),
)

export const posts = pgTable(
  'posts',
  {
    id: serial('id').primaryKey(),
    title: varchar('title'),
    slug: varchar('slug'),
    excerpt: varchar('excerpt'),
    content: jsonb('content'),
    commentsEnabled: boolean('comments_enabled').default(true),
    disclaimer: varchar('disclaimer'),
    media: varchar('media'),
    status: enum_posts_status('status'),
    publishDate: timestamp('publish_date', { mode: 'string', withTimezone: true, precision: 3 }),
    metaTitle: varchar('meta_title'),
    metaDescription: varchar('meta_description'),
    focusKeyword: varchar('focus_keyword'),
    imageAltText: varchar('image_alt_text'),
    externalLinks: varchar('external_links'),
    internalLinks: varchar('internal_links'),
    faq: varchar('faq'),
    author: integer('author_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    deleted_at: timestamp('deleted_at', { mode: 'string', withTimezone: true, precision: 3 }),
    impressions: numeric('impressions').default('0'),
    seoScore: integer('seo_score'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    posts_title_idx: uniqueIndex('posts_title_idx').on(columns.title),
    posts_slug_idx: uniqueIndex('posts_slug_idx').on(columns.slug),
    posts_author_idx: index('posts_author_idx').on(columns.author),
    posts_updated_at_idx: index('posts_updated_at_idx').on(columns.updatedAt),
    posts_created_at_idx: index('posts_created_at_idx').on(columns.createdAt),
  }),
)

export const posts_rels = pgTable(
  'posts_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    categoriesID: integer('categories_id'),
    tagsID: integer('tags_id'),
  },
  (columns) => ({
    order: index('posts_rels_order_idx').on(columns.order),
    parentIdx: index('posts_rels_parent_idx').on(columns.parent),
    pathIdx: index('posts_rels_path_idx').on(columns.path),
    posts_rels_categories_id_idx: index('posts_rels_categories_id_idx').on(columns.categoriesID),
    posts_rels_tags_id_idx: index('posts_rels_tags_id_idx').on(columns.tagsID),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [posts.id],
      name: 'posts_rels_parent_fk',
    }).onDelete('cascade'),
    categoriesIdFk: foreignKey({
      columns: [columns['categoriesID']],
      foreignColumns: [categories.id],
      name: 'posts_rels_categories_fk',
    }).onDelete('cascade'),
    tagsIdFk: foreignKey({
      columns: [columns['tagsID']],
      foreignColumns: [tags.id],
      name: 'posts_rels_tags_fk',
    }).onDelete('cascade'),
  }),
)

export const post_translation_entries = pgTable(
  'post_translation_entries',
  {
    id: serial('id').primaryKey(),
    post: integer('post_id')
      .notNull()
      .references(() => posts.id, {
        onDelete: 'set null',
      }),
    locale: enum_post_translation_entries_locale('locale').notNull(),
    title: varchar('title'),
    slug: varchar('slug'),
    excerpt: varchar('excerpt'),
    content: jsonb('content'),
    metaTitle: varchar('meta_title'),
    metaDescription: varchar('meta_description'),
    focusKeyword: varchar('focus_keyword'),
    imageAltText: varchar('image_alt_text'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    post_translation_entries_post_idx: index('post_translation_entries_post_idx').on(columns.post),
    post_translation_entries_updated_at_idx: index('post_translation_entries_updated_at_idx').on(
      columns.updatedAt,
    ),
    post_translation_entries_created_at_idx: index('post_translation_entries_created_at_idx').on(
      columns.createdAt,
    ),
  }),
)

export const tags = pgTable(
  'tags',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    slug: varchar('slug').notNull(),
    isVisible: boolean('is_visible').notNull().default(true),
    deleted_at: timestamp('deleted_at', { mode: 'string', withTimezone: true, precision: 3 }),
    createdBy: integer('created_by_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    tags_name_idx: uniqueIndex('tags_name_idx').on(columns.name),
    tags_slug_idx: uniqueIndex('tags_slug_idx').on(columns.slug),
    tags_created_by_idx: index('tags_created_by_idx').on(columns.createdBy),
    tags_updated_at_idx: index('tags_updated_at_idx').on(columns.updatedAt),
    tags_created_at_idx: index('tags_created_at_idx').on(columns.createdAt),
  }),
)

export const tags_rels = pgTable(
  'tags_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    postsID: integer('posts_id'),
  },
  (columns) => ({
    order: index('tags_rels_order_idx').on(columns.order),
    parentIdx: index('tags_rels_parent_idx').on(columns.parent),
    pathIdx: index('tags_rels_path_idx').on(columns.path),
    tags_rels_posts_id_idx: index('tags_rels_posts_id_idx').on(columns.postsID),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [tags.id],
      name: 'tags_rels_parent_fk',
    }).onDelete('cascade'),
    postsIdFk: foreignKey({
      columns: [columns['postsID']],
      foreignColumns: [posts.id],
      name: 'tags_rels_posts_fk',
    }).onDelete('cascade'),
  }),
)

export const notifications = pgTable(
  'notifications',
  {
    id: serial('id').primaryKey(),
    user: integer('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    title: varchar('title').notNull(),
    message: varchar('message').notNull(),
    type: enum_notifications_type('type').notNull().default('comment'),
    read: boolean('read').default(false),
    relatedPost: integer('related_post_id').references(() => posts.id, {
      onDelete: 'set null',
    }),
    relatedComment: integer('related_comment_id').references(() => comments.id, {
      onDelete: 'set null',
    }),
    fromUser: integer('from_user_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    notifications_user_idx: index('notifications_user_idx').on(columns.user),
    notifications_related_post_idx: index('notifications_related_post_idx').on(columns.relatedPost),
    notifications_related_comment_idx: index('notifications_related_comment_idx').on(
      columns.relatedComment,
    ),
    notifications_from_user_idx: index('notifications_from_user_idx').on(columns.fromUser),
    notifications_updated_at_idx: index('notifications_updated_at_idx').on(columns.updatedAt),
    notifications_created_at_idx: index('notifications_created_at_idx').on(columns.createdAt),
  }),
)

export const subscriptions = pgTable(
  'subscriptions',
  {
    id: serial('id').primaryKey(),
    email: varchar('email').notNull(),
    subscribed: boolean('subscribed').default(true),
    unsubscribedAt: timestamp('unsubscribed_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    subscriptions_email_idx: uniqueIndex('subscriptions_email_idx').on(columns.email),
    subscriptions_updated_at_idx: index('subscriptions_updated_at_idx').on(columns.updatedAt),
    subscriptions_created_at_idx: index('subscriptions_created_at_idx').on(columns.createdAt),
  }),
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_locked_documents_global_slug_idx: index('payload_locked_documents_global_slug_idx').on(
      columns.globalSlug,
    ),
    payload_locked_documents_updated_at_idx: index('payload_locked_documents_updated_at_idx').on(
      columns.updatedAt,
    ),
    payload_locked_documents_created_at_idx: index('payload_locked_documents_created_at_idx').on(
      columns.createdAt,
    ),
  }),
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    adminID: integer('admin_id'),
    usersID: integer('users_id'),
    mediaID: integer('media_id'),
    categoriesID: integer('categories_id'),
    commentsID: integer('comments_id'),
    likesID: integer('likes_id'),
    'post-logsID': integer('post_logs_id'),
    postsID: integer('posts_id'),
    'post-translation-entriesID': integer('post_translation_entries_id'),
    tagsID: integer('tags_id'),
    notificationsID: integer('notifications_id'),
    subscriptionsID: integer('subscriptions_id'),
  },
  (columns) => ({
    order: index('payload_locked_documents_rels_order_idx').on(columns.order),
    parentIdx: index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    pathIdx: index('payload_locked_documents_rels_path_idx').on(columns.path),
    payload_locked_documents_rels_admin_id_idx: index(
      'payload_locked_documents_rels_admin_id_idx',
    ).on(columns.adminID),
    payload_locked_documents_rels_users_id_idx: index(
      'payload_locked_documents_rels_users_id_idx',
    ).on(columns.usersID),
    payload_locked_documents_rels_media_id_idx: index(
      'payload_locked_documents_rels_media_id_idx',
    ).on(columns.mediaID),
    payload_locked_documents_rels_categories_id_idx: index(
      'payload_locked_documents_rels_categories_id_idx',
    ).on(columns.categoriesID),
    payload_locked_documents_rels_comments_id_idx: index(
      'payload_locked_documents_rels_comments_id_idx',
    ).on(columns.commentsID),
    payload_locked_documents_rels_likes_id_idx: index(
      'payload_locked_documents_rels_likes_id_idx',
    ).on(columns.likesID),
    payload_locked_documents_rels_post_logs_id_idx: index(
      'payload_locked_documents_rels_post_logs_id_idx',
    ).on(columns['post-logsID']),
    payload_locked_documents_rels_posts_id_idx: index(
      'payload_locked_documents_rels_posts_id_idx',
    ).on(columns.postsID),
    payload_locked_documents_rels_post_translation_entries_id_idx: index(
      'payload_locked_documents_rels_post_translation_entries_id_idx',
    ).on(columns['post-translation-entriesID']),
    payload_locked_documents_rels_tags_id_idx: index(
      'payload_locked_documents_rels_tags_id_idx',
    ).on(columns.tagsID),
    payload_locked_documents_rels_notifications_id_idx: index(
      'payload_locked_documents_rels_notifications_id_idx',
    ).on(columns.notificationsID),
    payload_locked_documents_rels_subscriptions_id_idx: index(
      'payload_locked_documents_rels_subscriptions_id_idx',
    ).on(columns.subscriptionsID),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    adminIdFk: foreignKey({
      columns: [columns['adminID']],
      foreignColumns: [admin.id],
      name: 'payload_locked_documents_rels_admin_fk',
    }).onDelete('cascade'),
    usersIdFk: foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    mediaIdFk: foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    categoriesIdFk: foreignKey({
      columns: [columns['categoriesID']],
      foreignColumns: [categories.id],
      name: 'payload_locked_documents_rels_categories_fk',
    }).onDelete('cascade'),
    commentsIdFk: foreignKey({
      columns: [columns['commentsID']],
      foreignColumns: [comments.id],
      name: 'payload_locked_documents_rels_comments_fk',
    }).onDelete('cascade'),
    likesIdFk: foreignKey({
      columns: [columns['likesID']],
      foreignColumns: [likes.id],
      name: 'payload_locked_documents_rels_likes_fk',
    }).onDelete('cascade'),
    'post-logsIdFk': foreignKey({
      columns: [columns['post-logsID']],
      foreignColumns: [post_logs.id],
      name: 'payload_locked_documents_rels_post_logs_fk',
    }).onDelete('cascade'),
    postsIdFk: foreignKey({
      columns: [columns['postsID']],
      foreignColumns: [posts.id],
      name: 'payload_locked_documents_rels_posts_fk',
    }).onDelete('cascade'),
    'post-translation-entriesIdFk': foreignKey({
      columns: [columns['post-translation-entriesID']],
      foreignColumns: [post_translation_entries.id],
      name: 'payload_locked_documents_rels_post_translation_entries_fk',
    }).onDelete('cascade'),
    tagsIdFk: foreignKey({
      columns: [columns['tagsID']],
      foreignColumns: [tags.id],
      name: 'payload_locked_documents_rels_tags_fk',
    }).onDelete('cascade'),
    notificationsIdFk: foreignKey({
      columns: [columns['notificationsID']],
      foreignColumns: [notifications.id],
      name: 'payload_locked_documents_rels_notifications_fk',
    }).onDelete('cascade'),
    subscriptionsIdFk: foreignKey({
      columns: [columns['subscriptionsID']],
      foreignColumns: [subscriptions.id],
      name: 'payload_locked_documents_rels_subscriptions_fk',
    }).onDelete('cascade'),
  }),
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_preferences_key_idx: index('payload_preferences_key_idx').on(columns.key),
    payload_preferences_updated_at_idx: index('payload_preferences_updated_at_idx').on(
      columns.updatedAt,
    ),
    payload_preferences_created_at_idx: index('payload_preferences_created_at_idx').on(
      columns.createdAt,
    ),
  }),
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    adminID: integer('admin_id'),
  },
  (columns) => ({
    order: index('payload_preferences_rels_order_idx').on(columns.order),
    parentIdx: index('payload_preferences_rels_parent_idx').on(columns.parent),
    pathIdx: index('payload_preferences_rels_path_idx').on(columns.path),
    payload_preferences_rels_admin_id_idx: index('payload_preferences_rels_admin_id_idx').on(
      columns.adminID,
    ),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    adminIdFk: foreignKey({
      columns: [columns['adminID']],
      foreignColumns: [admin.id],
      name: 'payload_preferences_rels_admin_fk',
    }).onDelete('cascade'),
  }),
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_migrations_updated_at_idx: index('payload_migrations_updated_at_idx').on(
      columns.updatedAt,
    ),
    payload_migrations_created_at_idx: index('payload_migrations_created_at_idx').on(
      columns.createdAt,
    ),
  }),
)

export const relations_admin = relations(admin, () => ({}))
export const relations_users = relations(users, () => ({}))
export const relations_media = relations(media, () => ({}))
export const relations_categories = relations(categories, ({ one }) => ({
  parent: one(categories, {
    fields: [categories.parent],
    references: [categories.id],
    relationName: 'parent',
  }),
  createdBy: one(users, {
    fields: [categories.createdBy],
    references: [users.id],
    relationName: 'createdBy',
  }),
}))
export const relations_comments = relations(comments, ({ one }) => ({
  post: one(posts, {
    fields: [comments.post],
    references: [posts.id],
    relationName: 'post',
  }),
  user: one(users, {
    fields: [comments.user],
    references: [users.id],
    relationName: 'user',
  }),
  parent: one(comments, {
    fields: [comments.parent],
    references: [comments.id],
    relationName: 'parent',
  }),
}))
export const relations_likes = relations(likes, ({ one }) => ({
  post: one(posts, {
    fields: [likes.post],
    references: [posts.id],
    relationName: 'post',
  }),
  user: one(users, {
    fields: [likes.user],
    references: [users.id],
    relationName: 'user',
  }),
}))
export const relations_post_logs = relations(post_logs, ({ one }) => ({
  post: one(posts, {
    fields: [post_logs.post],
    references: [posts.id],
    relationName: 'post',
  }),
  user: one(users, {
    fields: [post_logs.user],
    references: [users.id],
    relationName: 'user',
  }),
}))
export const relations_posts_rels = relations(posts_rels, ({ one }) => ({
  parent: one(posts, {
    fields: [posts_rels.parent],
    references: [posts.id],
    relationName: '_rels',
  }),
  categoriesID: one(categories, {
    fields: [posts_rels.categoriesID],
    references: [categories.id],
    relationName: 'categories',
  }),
  tagsID: one(tags, {
    fields: [posts_rels.tagsID],
    references: [tags.id],
    relationName: 'tags',
  }),
}))
export const relations_posts = relations(posts, ({ one, many }) => ({
  author: one(users, {
    fields: [posts.author],
    references: [users.id],
    relationName: 'author',
  }),
  _rels: many(posts_rels, {
    relationName: '_rels',
  }),
}))
export const relations_post_translation_entries = relations(
  post_translation_entries,
  ({ one }) => ({
    post: one(posts, {
      fields: [post_translation_entries.post],
      references: [posts.id],
      relationName: 'post',
    }),
  }),
)
export const relations_tags_rels = relations(tags_rels, ({ one }) => ({
  parent: one(tags, {
    fields: [tags_rels.parent],
    references: [tags.id],
    relationName: '_rels',
  }),
  postsID: one(posts, {
    fields: [tags_rels.postsID],
    references: [posts.id],
    relationName: 'posts',
  }),
}))
export const relations_tags = relations(tags, ({ one, many }) => ({
  createdBy: one(users, {
    fields: [tags.createdBy],
    references: [users.id],
    relationName: 'createdBy',
  }),
  _rels: many(tags_rels, {
    relationName: '_rels',
  }),
}))
export const relations_notifications = relations(notifications, ({ one }) => ({
  user: one(users, {
    fields: [notifications.user],
    references: [users.id],
    relationName: 'user',
  }),
  relatedPost: one(posts, {
    fields: [notifications.relatedPost],
    references: [posts.id],
    relationName: 'relatedPost',
  }),
  relatedComment: one(comments, {
    fields: [notifications.relatedComment],
    references: [comments.id],
    relationName: 'relatedComment',
  }),
  fromUser: one(users, {
    fields: [notifications.fromUser],
    references: [users.id],
    relationName: 'fromUser',
  }),
}))
export const relations_subscriptions = relations(subscriptions, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    adminID: one(admin, {
      fields: [payload_locked_documents_rels.adminID],
      references: [admin.id],
      relationName: 'admin',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    categoriesID: one(categories, {
      fields: [payload_locked_documents_rels.categoriesID],
      references: [categories.id],
      relationName: 'categories',
    }),
    commentsID: one(comments, {
      fields: [payload_locked_documents_rels.commentsID],
      references: [comments.id],
      relationName: 'comments',
    }),
    likesID: one(likes, {
      fields: [payload_locked_documents_rels.likesID],
      references: [likes.id],
      relationName: 'likes',
    }),
    'post-logsID': one(post_logs, {
      fields: [payload_locked_documents_rels['post-logsID']],
      references: [post_logs.id],
      relationName: 'post-logs',
    }),
    postsID: one(posts, {
      fields: [payload_locked_documents_rels.postsID],
      references: [posts.id],
      relationName: 'posts',
    }),
    'post-translation-entriesID': one(post_translation_entries, {
      fields: [payload_locked_documents_rels['post-translation-entriesID']],
      references: [post_translation_entries.id],
      relationName: 'post-translation-entries',
    }),
    tagsID: one(tags, {
      fields: [payload_locked_documents_rels.tagsID],
      references: [tags.id],
      relationName: 'tags',
    }),
    notificationsID: one(notifications, {
      fields: [payload_locked_documents_rels.notificationsID],
      references: [notifications.id],
      relationName: 'notifications',
    }),
    subscriptionsID: one(subscriptions, {
      fields: [payload_locked_documents_rels.subscriptionsID],
      references: [subscriptions.id],
      relationName: 'subscriptions',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    adminID: one(admin, {
      fields: [payload_preferences_rels.adminID],
      references: [admin.id],
      relationName: 'admin',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))

type DatabaseSchema = {
  enum_users_role: typeof enum_users_role
  enum_comments_status: typeof enum_comments_status
  enum_likes_type: typeof enum_likes_type
  enum_post_logs_action: typeof enum_post_logs_action
  enum_posts_status: typeof enum_posts_status
  enum_post_translation_entries_locale: typeof enum_post_translation_entries_locale
  enum_notifications_type: typeof enum_notifications_type
  admin: typeof admin
  users: typeof users
  media: typeof media
  categories: typeof categories
  comments: typeof comments
  likes: typeof likes
  post_logs: typeof post_logs
  posts: typeof posts
  posts_rels: typeof posts_rels
  post_translation_entries: typeof post_translation_entries
  tags: typeof tags
  tags_rels: typeof tags_rels
  notifications: typeof notifications
  subscriptions: typeof subscriptions
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  relations_admin: typeof relations_admin
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_categories: typeof relations_categories
  relations_comments: typeof relations_comments
  relations_likes: typeof relations_likes
  relations_post_logs: typeof relations_post_logs
  relations_posts_rels: typeof relations_posts_rels
  relations_posts: typeof relations_posts
  relations_post_translation_entries: typeof relations_post_translation_entries
  relations_tags_rels: typeof relations_tags_rels
  relations_tags: typeof relations_tags
  relations_notifications: typeof relations_notifications
  relations_subscriptions: typeof relations_subscriptions
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
}

// Augmentation for Payload Postgres adapter (module may not be resolved at type-check time)
// @ts-expect-error - @payloadcms/db-postgres/types may not be present in all environments
declare module '@payloadcms/db-postgres/types' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
