/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  serial,
  timestamp,
  numeric,
  type AnyPgColumn,
  jsonb,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum_users_role = pgEnum('enum_users_role', ['admin', 'author', 'user'])
export const enum_comments_status = pgEnum('enum_comments_status', [
  'pending',
  'approved',
  'rejected',
])
export const enum_post_logs_action = pgEnum('enum_post_logs_action', ['create', 'update', 'delete'])
export const enum_posts_status = pgEnum('enum_posts_status', [
  'draft',
  'published',
  'pending_approval',
])
export const enum_posts_template = pgEnum('enum_posts_template', ['standard', 'full-width'])

export const users_social_links = pgTable(
  'users_social_links',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    platform: varchar('platform'),
    url: varchar('url'),
  },
  (columns) => ({
    _orderIdx: index('users_social_links_order_idx').on(columns._order),
    _parentIDIdx: index('users_social_links_parent_id_idx').on(columns._parentID),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_social_links_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    username: varchar('username').notNull(),
    displayName: varchar('display_name').notNull(),
    bio: varchar('bio'),
    profileImage: integer('profile_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    role: enum_users_role('role').notNull().default('author'),
    uid: varchar('uid').notNull(),
    lastLogin: timestamp('last_login', { mode: 'string', withTimezone: true, precision: 3 }),
    deleted_at: timestamp('deleted_at', { mode: 'string', withTimezone: true, precision: 3 }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts').default('0'),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => ({
    users_username_idx: uniqueIndex('users_username_idx').on(columns.username),
    users_profile_image_idx: index('users_profile_image_idx').on(columns.profileImage),
    users_uid_idx: uniqueIndex('users_uid_idx').on(columns.uid),
    users_updated_at_idx: index('users_updated_at_idx').on(columns.updatedAt),
    users_created_at_idx: index('users_created_at_idx').on(columns.createdAt),
    users_email_idx: uniqueIndex('users_email_idx').on(columns.email),
  }),
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    url: varchar('url').notNull(),
    alt: varchar('alt'),
    caption: varchar('caption'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    media_updated_at_idx: index('media_updated_at_idx').on(columns.updatedAt),
    media_created_at_idx: index('media_created_at_idx').on(columns.createdAt),
  }),
)

export const categories = pgTable(
  'categories',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    slug: varchar('slug').notNull(),
    deleted_at: timestamp('deleted_at', { mode: 'string', withTimezone: true, precision: 3 }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    categories_name_idx: uniqueIndex('categories_name_idx').on(columns.name),
    categories_slug_idx: uniqueIndex('categories_slug_idx').on(columns.slug),
    categories_updated_at_idx: index('categories_updated_at_idx').on(columns.updatedAt),
    categories_created_at_idx: index('categories_created_at_idx').on(columns.createdAt),
  }),
)

export const comments = pgTable(
  'comments',
  {
    id: serial('id').primaryKey(),
    post: integer('post_id')
      .notNull()
      .references(() => posts.id, {
        onDelete: 'set null',
      }),
    user: integer('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    content: varchar('content').notNull(),
    status: enum_comments_status('status').default('pending'),
    parent: integer('parent_id').references((): AnyPgColumn => comments.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    comments_post_idx: index('comments_post_idx').on(columns.post),
    comments_user_idx: index('comments_user_idx').on(columns.user),
    comments_parent_idx: index('comments_parent_idx').on(columns.parent),
    comments_updated_at_idx: index('comments_updated_at_idx').on(columns.updatedAt),
    comments_created_at_idx: index('comments_created_at_idx').on(columns.createdAt),
  }),
)

export const likes = pgTable(
  'likes',
  {
    id: serial('id').primaryKey(),
    post: integer('post_id')
      .notNull()
      .references(() => posts.id, {
        onDelete: 'set null',
      }),
    user: integer('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    likes_post_idx: index('likes_post_idx').on(columns.post),
    likes_user_idx: index('likes_user_idx').on(columns.user),
    likes_updated_at_idx: index('likes_updated_at_idx').on(columns.updatedAt),
    likes_created_at_idx: index('likes_created_at_idx').on(columns.createdAt),
  }),
)

export const post_logs = pgTable(
  'post_logs',
  {
    id: serial('id').primaryKey(),
    post: integer('post_id')
      .notNull()
      .references(() => posts.id, {
        onDelete: 'set null',
      }),
    user: integer('user_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    action: enum_post_logs_action('action').notNull(),
    timestamp: timestamp('timestamp', { mode: 'string', withTimezone: true, precision: 3 }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    post_logs_post_idx: index('post_logs_post_idx').on(columns.post),
    post_logs_user_idx: index('post_logs_user_idx').on(columns.user),
    post_logs_updated_at_idx: index('post_logs_updated_at_idx').on(columns.updatedAt),
    post_logs_created_at_idx: index('post_logs_created_at_idx').on(columns.createdAt),
  }),
)

export const posts = pgTable(
  'posts',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    slug: varchar('slug').notNull(),
    excerpt: varchar('excerpt'),
    content: jsonb('content'),
    media: integer('media_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    status: enum_posts_status('status').notNull(),
    publishDate: timestamp('publish_date', { mode: 'string', withTimezone: true, precision: 3 }),
    metaTitle: varchar('meta_title'),
    metaDescription: varchar('meta_description'),
    template: enum_posts_template('template'),
    author: integer('author_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    deleted_at: timestamp('deleted_at', { mode: 'string', withTimezone: true, precision: 3 }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    posts_slug_idx: uniqueIndex('posts_slug_idx').on(columns.slug),
    posts_media_idx: index('posts_media_idx').on(columns.media),
    posts_author_idx: index('posts_author_idx').on(columns.author),
    posts_updated_at_idx: index('posts_updated_at_idx').on(columns.updatedAt),
    posts_created_at_idx: index('posts_created_at_idx').on(columns.createdAt),
  }),
)

export const posts_rels = pgTable(
  'posts_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    categoriesID: integer('categories_id'),
    tagsID: integer('tags_id'),
  },
  (columns) => ({
    order: index('posts_rels_order_idx').on(columns.order),
    parentIdx: index('posts_rels_parent_idx').on(columns.parent),
    pathIdx: index('posts_rels_path_idx').on(columns.path),
    posts_rels_categories_id_idx: index('posts_rels_categories_id_idx').on(columns.categoriesID),
    posts_rels_tags_id_idx: index('posts_rels_tags_id_idx').on(columns.tagsID),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [posts.id],
      name: 'posts_rels_parent_fk',
    }).onDelete('cascade'),
    categoriesIdFk: foreignKey({
      columns: [columns['categoriesID']],
      foreignColumns: [categories.id],
      name: 'posts_rels_categories_fk',
    }).onDelete('cascade'),
    tagsIdFk: foreignKey({
      columns: [columns['tagsID']],
      foreignColumns: [tags.id],
      name: 'posts_rels_tags_fk',
    }).onDelete('cascade'),
  }),
)

export const tags = pgTable(
  'tags',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    slug: varchar('slug').notNull(),
    deleted_at: timestamp('deleted_at', { mode: 'string', withTimezone: true, precision: 3 }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    tags_name_idx: uniqueIndex('tags_name_idx').on(columns.name),
    tags_slug_idx: uniqueIndex('tags_slug_idx').on(columns.slug),
    tags_updated_at_idx: index('tags_updated_at_idx').on(columns.updatedAt),
    tags_created_at_idx: index('tags_created_at_idx').on(columns.createdAt),
  }),
)

export const tags_rels = pgTable(
  'tags_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    postsID: integer('posts_id'),
  },
  (columns) => ({
    order: index('tags_rels_order_idx').on(columns.order),
    parentIdx: index('tags_rels_parent_idx').on(columns.parent),
    pathIdx: index('tags_rels_path_idx').on(columns.path),
    tags_rels_posts_id_idx: index('tags_rels_posts_id_idx').on(columns.postsID),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [tags.id],
      name: 'tags_rels_parent_fk',
    }).onDelete('cascade'),
    postsIdFk: foreignKey({
      columns: [columns['postsID']],
      foreignColumns: [posts.id],
      name: 'tags_rels_posts_fk',
    }).onDelete('cascade'),
  }),
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_locked_documents_global_slug_idx: index('payload_locked_documents_global_slug_idx').on(
      columns.globalSlug,
    ),
    payload_locked_documents_updated_at_idx: index('payload_locked_documents_updated_at_idx').on(
      columns.updatedAt,
    ),
    payload_locked_documents_created_at_idx: index('payload_locked_documents_created_at_idx').on(
      columns.createdAt,
    ),
  }),
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
    mediaID: integer('media_id'),
    categoriesID: integer('categories_id'),
    commentsID: integer('comments_id'),
    likesID: integer('likes_id'),
    'post-logsID': integer('post_logs_id'),
    postsID: integer('posts_id'),
    tagsID: integer('tags_id'),
  },
  (columns) => ({
    order: index('payload_locked_documents_rels_order_idx').on(columns.order),
    parentIdx: index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    pathIdx: index('payload_locked_documents_rels_path_idx').on(columns.path),
    payload_locked_documents_rels_users_id_idx: index(
      'payload_locked_documents_rels_users_id_idx',
    ).on(columns.usersID),
    payload_locked_documents_rels_media_id_idx: index(
      'payload_locked_documents_rels_media_id_idx',
    ).on(columns.mediaID),
    payload_locked_documents_rels_categories_id_idx: index(
      'payload_locked_documents_rels_categories_id_idx',
    ).on(columns.categoriesID),
    payload_locked_documents_rels_comments_id_idx: index(
      'payload_locked_documents_rels_comments_id_idx',
    ).on(columns.commentsID),
    payload_locked_documents_rels_likes_id_idx: index(
      'payload_locked_documents_rels_likes_id_idx',
    ).on(columns.likesID),
    payload_locked_documents_rels_post_logs_id_idx: index(
      'payload_locked_documents_rels_post_logs_id_idx',
    ).on(columns['post-logsID']),
    payload_locked_documents_rels_posts_id_idx: index(
      'payload_locked_documents_rels_posts_id_idx',
    ).on(columns.postsID),
    payload_locked_documents_rels_tags_id_idx: index(
      'payload_locked_documents_rels_tags_id_idx',
    ).on(columns.tagsID),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    usersIdFk: foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    mediaIdFk: foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    categoriesIdFk: foreignKey({
      columns: [columns['categoriesID']],
      foreignColumns: [categories.id],
      name: 'payload_locked_documents_rels_categories_fk',
    }).onDelete('cascade'),
    commentsIdFk: foreignKey({
      columns: [columns['commentsID']],
      foreignColumns: [comments.id],
      name: 'payload_locked_documents_rels_comments_fk',
    }).onDelete('cascade'),
    likesIdFk: foreignKey({
      columns: [columns['likesID']],
      foreignColumns: [likes.id],
      name: 'payload_locked_documents_rels_likes_fk',
    }).onDelete('cascade'),
    'post-logsIdFk': foreignKey({
      columns: [columns['post-logsID']],
      foreignColumns: [post_logs.id],
      name: 'payload_locked_documents_rels_post_logs_fk',
    }).onDelete('cascade'),
    postsIdFk: foreignKey({
      columns: [columns['postsID']],
      foreignColumns: [posts.id],
      name: 'payload_locked_documents_rels_posts_fk',
    }).onDelete('cascade'),
    tagsIdFk: foreignKey({
      columns: [columns['tagsID']],
      foreignColumns: [tags.id],
      name: 'payload_locked_documents_rels_tags_fk',
    }).onDelete('cascade'),
  }),
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_preferences_key_idx: index('payload_preferences_key_idx').on(columns.key),
    payload_preferences_updated_at_idx: index('payload_preferences_updated_at_idx').on(
      columns.updatedAt,
    ),
    payload_preferences_created_at_idx: index('payload_preferences_created_at_idx').on(
      columns.createdAt,
    ),
  }),
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => ({
    order: index('payload_preferences_rels_order_idx').on(columns.order),
    parentIdx: index('payload_preferences_rels_parent_idx').on(columns.parent),
    pathIdx: index('payload_preferences_rels_path_idx').on(columns.path),
    payload_preferences_rels_users_id_idx: index('payload_preferences_rels_users_id_idx').on(
      columns.usersID,
    ),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    usersIdFk: foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  }),
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_migrations_updated_at_idx: index('payload_migrations_updated_at_idx').on(
      columns.updatedAt,
    ),
    payload_migrations_created_at_idx: index('payload_migrations_created_at_idx').on(
      columns.createdAt,
    ),
  }),
)

export const relations_users_social_links = relations(users_social_links, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_social_links._parentID],
    references: [users.id],
    relationName: 'socialLinks',
  }),
}))
export const relations_users = relations(users, ({ one, many }) => ({
  profileImage: one(media, {
    fields: [users.profileImage],
    references: [media.id],
    relationName: 'profileImage',
  }),
  socialLinks: many(users_social_links, {
    relationName: 'socialLinks',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_categories = relations(categories, () => ({}))
export const relations_comments = relations(comments, ({ one }) => ({
  post: one(posts, {
    fields: [comments.post],
    references: [posts.id],
    relationName: 'post',
  }),
  user: one(users, {
    fields: [comments.user],
    references: [users.id],
    relationName: 'user',
  }),
  parent: one(comments, {
    fields: [comments.parent],
    references: [comments.id],
    relationName: 'parent',
  }),
}))
export const relations_likes = relations(likes, ({ one }) => ({
  post: one(posts, {
    fields: [likes.post],
    references: [posts.id],
    relationName: 'post',
  }),
  user: one(users, {
    fields: [likes.user],
    references: [users.id],
    relationName: 'user',
  }),
}))
export const relations_post_logs = relations(post_logs, ({ one }) => ({
  post: one(posts, {
    fields: [post_logs.post],
    references: [posts.id],
    relationName: 'post',
  }),
  user: one(users, {
    fields: [post_logs.user],
    references: [users.id],
    relationName: 'user',
  }),
}))
export const relations_posts_rels = relations(posts_rels, ({ one }) => ({
  parent: one(posts, {
    fields: [posts_rels.parent],
    references: [posts.id],
    relationName: '_rels',
  }),
  categoriesID: one(categories, {
    fields: [posts_rels.categoriesID],
    references: [categories.id],
    relationName: 'categories',
  }),
  tagsID: one(tags, {
    fields: [posts_rels.tagsID],
    references: [tags.id],
    relationName: 'tags',
  }),
}))
export const relations_posts = relations(posts, ({ one, many }) => ({
  media: one(media, {
    fields: [posts.media],
    references: [media.id],
    relationName: 'media',
  }),
  author: one(users, {
    fields: [posts.author],
    references: [users.id],
    relationName: 'author',
  }),
  _rels: many(posts_rels, {
    relationName: '_rels',
  }),
}))
export const relations_tags_rels = relations(tags_rels, ({ one }) => ({
  parent: one(tags, {
    fields: [tags_rels.parent],
    references: [tags.id],
    relationName: '_rels',
  }),
  postsID: one(posts, {
    fields: [tags_rels.postsID],
    references: [posts.id],
    relationName: 'posts',
  }),
}))
export const relations_tags = relations(tags, ({ many }) => ({
  _rels: many(tags_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    categoriesID: one(categories, {
      fields: [payload_locked_documents_rels.categoriesID],
      references: [categories.id],
      relationName: 'categories',
    }),
    commentsID: one(comments, {
      fields: [payload_locked_documents_rels.commentsID],
      references: [comments.id],
      relationName: 'comments',
    }),
    likesID: one(likes, {
      fields: [payload_locked_documents_rels.likesID],
      references: [likes.id],
      relationName: 'likes',
    }),
    'post-logsID': one(post_logs, {
      fields: [payload_locked_documents_rels['post-logsID']],
      references: [post_logs.id],
      relationName: 'post-logs',
    }),
    postsID: one(posts, {
      fields: [payload_locked_documents_rels.postsID],
      references: [posts.id],
      relationName: 'posts',
    }),
    tagsID: one(tags, {
      fields: [payload_locked_documents_rels.tagsID],
      references: [tags.id],
      relationName: 'tags',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))

type DatabaseSchema = {
  enum_users_role: typeof enum_users_role
  enum_comments_status: typeof enum_comments_status
  enum_post_logs_action: typeof enum_post_logs_action
  enum_posts_status: typeof enum_posts_status
  enum_posts_template: typeof enum_posts_template
  users_social_links: typeof users_social_links
  users: typeof users
  media: typeof media
  categories: typeof categories
  comments: typeof comments
  likes: typeof likes
  post_logs: typeof post_logs
  posts: typeof posts
  posts_rels: typeof posts_rels
  tags: typeof tags
  tags_rels: typeof tags_rels
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  relations_users_social_links: typeof relations_users_social_links
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_categories: typeof relations_categories
  relations_comments: typeof relations_comments
  relations_likes: typeof relations_likes
  relations_post_logs: typeof relations_post_logs
  relations_posts_rels: typeof relations_posts_rels
  relations_posts: typeof relations_posts
  relations_tags_rels: typeof relations_tags_rels
  relations_tags: typeof relations_tags
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
