import type { Metadata } from 'next'
import Navbar from '@/components/navbar'
import Footer from '@/components/footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className="w-full h-full flex flex-col justify-between items-center bg-background">
      <Navbar />
      <div className="h-full mt-20 container mx-auto xs:px-5 px-3">{children}</div>
      <Footer />
    </div>
  )
}
